name: railway_system
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter
    flutter_dotenv: ^5.2.1
    mysql_client: ^0.0.27
    provider: ^6.1.2
    qr_flutter: ^4.1.0
    shared_preferences: ^2.3.3
    url_launcher: ^6.3.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/high-speed-train.png
        - assets/images/railway.png
        - assets/images/arrow.png
        - assets/images/Google.png
        - assets/images/Apple.png
        - .env
